fix yaml syntax

diff --git a/.github/workflows/docker-wf.yml b/.github/workflows/docker-wf.yml
--- a/.github/workflows/docker-wf.yml
+++ b/.github/workflows/docker-wf.yml
@@ -17,19 +17,19 @@ jobs:
       run: docker-compose up -d
       
     - name: Run Tests
-        id: test
-        run: |
-          result=$(docker exec -it ikura_app python3 app_test.py)
-          echo "::set-output name=result::$result"
+      id: test
+      run: |
+        result=$(docker exec -it ikura_app python3 app_test.py)
+        echo "::set-output name=result::$result"
 
-      - name: Check test results
-        run: |
-          if [[ "${{ steps.test.outputs.result }}" == *"Tests Passed"* ]]; then
-            echo "Tests passed!"
-          else
-            echo "Tests failed!"
-            exit 1
-          fi
+    - name: Check test results
+      run: |
+        if [[ "${{ steps.test.outputs.result }}" == *"Tests Passed"* ]]; then
+          echo "Tests passed!"
+        else
+          echo "Tests failed!"
+          exit 1
+        fi
  
     - name: Tear down services
       run: docker-compose down -v
