multiple fixes for compose and workflow

diff --git a/.github/workflows/docker-wf.yml b/.github/workflows/docker-wf.yml
--- a/.github/workflows/docker-wf.yml
+++ b/.github/workflows/docker-wf.yml
@@ -15,12 +15,21 @@ jobs:
 
     - name: Start Docker Compose
       run: docker-compose up -d
-
-    - name: Debug - Show Docker Compose logs
-      run: docker-compose logs
       
-    - name: check server status
-      run: curl localhost:5000/test
+    - name: Run Tests
+        id: test
+        run: |
+          result=$(docker exec -it ikura_app python3 app_test.py)
+          echo "::set-output name=result::$result"
+
+      - name: Check test results
+        run: |
+          if [[ "${{ steps.test.outputs.result }}" == *"Tests Passed"* ]]; then
+            echo "Tests passed!"
+          else
+            echo "Tests failed!"
+            exit 1
+          fi
  
-    - name: Stop Docker Compose
+    - name: Tear down services
       run: docker-compose down -v
